### ISSUE TITLE
Brave Wallet - myKeyValid sig at last!

### ISSUE THREAD

**Issue by masanaikeshima** [Loopring/loopring_sdk#34]
Hi Loopring!

I've got a Brave Wallet and when I try to Activate my wallet I keep getting the error myKeyValid sig at last!

![CleanShot 2021-12-22 at 13 57 37](https://user-images.githubusercontent.com/7580706/147103989-105accf3-15ef-443a-933a-fe59ba5a8b6f.png)

I can see from the Source Maps that this is from:
https://github.com/Loopring/loopring_sdk/blob/1830d5451ba4e9b1739843ed1966e4c4363bb22e/src/api/ethereum/metaMask.ts

Steps I took that resulted in this:

- Downloaded Brave Browser
- Created new Brave Wallet
- Bought ETH from coinbase
- Sent ETH from coinbase to Brave Wallet
- Went to https://loopring.io/ to transfer from Brave Wallet to Loopring Wallet
- I can see this transfer was succesful as its in Etherscan (https://etherscan.io/address/0x4B581710DBeC04d914f51141e89293db0eaeEc0e)
- Clicking Activate Wallet prompts for my Brave Wallet signature which I can confirm.
- Loopring flashes to show the wallet is activated, then flips back to the Activate now modal

![CleanShot 2021-12-22 at 14 01 01](https://user-images.githubusercontent.com/7580706/147104444-6fd63872-335b-4e39-a53b-4411344cbf71.png)

Device:

- MacOS 11.6
- Browser: Brave Browser v 1.32.113

Thanks and congrats on the new launch!

**Comment by windatang** [comment]
interesting, we never support for brave wallet to our website
what step you connect it. please let me know
but for current now, you can export your private key to metamask to connect loopring website... then you can active your account. If still not able to active ask custom service for help 
close your issue add a new one to todo list
