### ISSUE TITLE
Breaking Change in patch version from 1.10.1 to 1.10.2

### ISSUE THREAD

**Issue by elationbase** [Loopring/loopring_sdk#46]
In `@loopring-web/loopring-sdk => 1.10.1` 
user can import
`import { VALID_UNTIL } from '@loopring-web/loopring-sdk';`

Starting In `@loopring-web/loopring-sdk => 1.10.2` 
`VALID_UNTIL` is not available

**Comment by windatang** [comment]
yes this const removed

**Comment by windatang** [comment]
It should defined by Client-side, please view the Demo mock data as the example

**Comment by elationbase** [comment]
Thank you, but this is a breaking change in your library and should not be deleted in a minor or patch version.
My app is now not building unless I change code. I guess I will need to force version. No more `^`.
