### ISSUE TITLE
ECDSA signature fails on some CIDs - (Mint NFT Failed)

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring_sdk#47]
Issue - https://github.com/Loopring/loopring-wallet-feedback/issues/181#issue-1153392035

Proposed Solution - https://github.com/Loopring/loopring-wallet-feedback/issues/181#issuecomment-1063357136

**Comment by fudgebucket27** [comment]
Hey itsmonty.eth and I did some debugging with problem NFTs. Here is what we found https://github.com/Loopring/loopring-wallet-feedback/issues/181#issuecomment-1105688655
